//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFLStock.UI.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings_AFLStock_Logins : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_AFLStock_Logins defaultInstance = ((Settings_AFLStock_Logins)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_AFLStock_Logins())));
        
        public static Settings_AFLStock_Logins Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A5E3A24DFC195CA398867CD26D8987E0")]
        public string AFL_Super {
            get {
                return ((string)(this["AFL_Super"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B8C2AE332FD9AF9646B4AB0243079E21")]
        public string Muhariz_Super {
            get {
                return ((string)(this["Muhariz_Super"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8D5A02CA43A1824BCD7AC8FA087905C7")]
        public string Priya_user {
            get {
                return ((string)(this["Priya_user"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73289D7EF597CFA28BFFEF98806EB563")]
        public string Vasana_user {
            get {
                return ((string)(this["Vasana_user"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3E5E45FEEEF96B5D078BE7CD7C7E6AD")]
        public string Guest_reader {
            get {
                return ((string)(this["Guest_reader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A5E3A24DFC195CA398867CD26D8987E0")]
        public string AFL_Super_Test {
            get {
                return ((string)(this["AFL_Super_Test"]));
            }
        }
    }
}
