//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFLStock.WCF.Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrder_POCO", Namespace="http://schemas.datacontract.org/2004/07/AFLStock.Entities")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrder_POCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseOrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AFLStock.WCF.Client.ServiceReference.PurchaseOrderDetail_POCO[] PurchaseOrderDetailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalReferenceID {
            get {
                return this.ExternalReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalReferenceIDField, value) != true)) {
                    this.ExternalReferenceIDField = value;
                    this.RaisePropertyChanged("ExternalReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderDate {
            get {
                return this.PurchaseOrderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrderDateField, value) != true)) {
                    this.PurchaseOrderDateField = value;
                    this.RaisePropertyChanged("PurchaseOrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AFLStock.WCF.Client.ServiceReference.PurchaseOrderDetail_POCO[] PurchaseOrderDetailList {
            get {
                return this.PurchaseOrderDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrderDetailListField, value) != true)) {
                    this.PurchaseOrderDetailListField = value;
                    this.RaisePropertyChanged("PurchaseOrderDetailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetail_POCO", Namespace="http://schemas.datacontract.org/2004/07/AFLStock.Entities")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderDetail_POCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCategory {
            get {
                return this.StockCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCategoryField, value) != true)) {
                    this.StockCategoryField = value;
                    this.RaisePropertyChanged("StockCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrder_POCO", Namespace="http://schemas.datacontract.org/2004/07/AFLStock.Entities")]
    [System.SerializableAttribute()]
    public partial class SalesOrder_POCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesOrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AFLStock.WCF.Client.ServiceReference.SalesOrderDetail_POCO[] SalesOrderDetailListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalReferenceID {
            get {
                return this.ExternalReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalReferenceIDField, value) != true)) {
                    this.ExternalReferenceIDField = value;
                    this.RaisePropertyChanged("ExternalReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrderDate {
            get {
                return this.SalesOrderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesOrderDateField, value) != true)) {
                    this.SalesOrderDateField = value;
                    this.RaisePropertyChanged("SalesOrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AFLStock.WCF.Client.ServiceReference.SalesOrderDetail_POCO[] SalesOrderDetailList {
            get {
                return this.SalesOrderDetailListField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesOrderDetailListField, value) != true)) {
                    this.SalesOrderDetailListField = value;
                    this.RaisePropertyChanged("SalesOrderDetailList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderDetail_POCO", Namespace="http://schemas.datacontract.org/2004/07/AFLStock.Entities")]
    [System.SerializableAttribute()]
    public partial class SalesOrderDetail_POCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCategory {
            get {
                return this.StockCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCategoryField, value) != true)) {
                    this.StockCategoryField = value;
                    this.RaisePropertyChanged("StockCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockItemMaster_POCO", Namespace="http://schemas.datacontract.org/2004/07/AFLStock.Entities")]
    [System.SerializableAttribute()]
    public partial class StockItemMaster_POCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasQuantityListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] QuantityListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignNumber {
            get {
                return this.DesignNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignNumberField, value) != true)) {
                    this.DesignNumberField = value;
                    this.RaisePropertyChanged("DesignNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasQuantityList {
            get {
                return this.HasQuantityListField;
            }
            set {
                if ((this.HasQuantityListField.Equals(value) != true)) {
                    this.HasQuantityListField = value;
                    this.RaisePropertyChanged("HasQuantityList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] QuantityList {
            get {
                return this.QuantityListField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityListField, value) != true)) {
                    this.QuantityListField = value;
                    this.RaisePropertyChanged("QuantityList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockCategory {
            get {
                return this.StockCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.StockCategoryField, value) != true)) {
                    this.StockCategoryField = value;
                    this.RaisePropertyChanged("StockCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode {
            get {
                return this.SubCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCodeField, value) != true)) {
                    this.SubCodeField = value;
                    this.RaisePropertyChanged("SubCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAFLStockService")]
    public interface IAFLStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetPurchaseOrders_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetPurchaseOrders_SimplifiedResponse")]
        AFLStock.WCF.Client.ServiceReference.PurchaseOrder_POCO[] GetPurchaseOrders_Simplified();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetPurchaseOrders_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetPurchaseOrders_SimplifiedResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.PurchaseOrder_POCO[]> GetPurchaseOrders_SimplifiedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetSalesOrders_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetSalesOrders_SimplifiedResponse")]
        AFLStock.WCF.Client.ServiceReference.SalesOrder_POCO[] GetSalesOrders_Simplified();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetSalesOrders_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetSalesOrders_SimplifiedResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.SalesOrder_POCO[]> GetSalesOrders_SimplifiedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/TotalStockValue", ReplyAction="http://tempuri.org/IAFLStockService/TotalStockValueResponse")]
        double TotalStockValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/TotalStockValue", ReplyAction="http://tempuri.org/IAFLStockService/TotalStockValueResponse")]
        System.Threading.Tasks.Task<double> TotalStockValueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsAll_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsAll_SimplifiedResponse")]
        AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsAll_Simplified();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsAll_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsAll_SimplifiedResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsAll_SimplifiedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategory_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategory_SimplifiedResponse")]
        AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategory_Simplified(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategory_Simplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategory_SimplifiedResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategory_SimplifiedAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumber_Simplifie" +
            "d", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumber_Simplifie" +
            "dResponse")]
        AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategoryDesignNumber_Simplified(int catID, string designNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumber_Simplifie" +
            "d", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumber_Simplifie" +
            "dResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategoryDesignNumber_SimplifiedAsync(int catID, string designNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumberSubCode_Si" +
            "mplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumberSubCode_Si" +
            "mplifiedResponse")]
        AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategoryDesignNumberSubCode_Simplified(int catID, string designNumber, string subCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumberSubCode_Si" +
            "mplified", ReplyAction="http://tempuri.org/IAFLStockService/GetStockItemsByCategoryDesignNumberSubCode_Si" +
            "mplifiedResponse")]
        System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategoryDesignNumberSubCode_SimplifiedAsync(int catID, string designNumber, string subCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAFLStockServiceChannel : AFLStock.WCF.Client.ServiceReference.IAFLStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AFLStockServiceClient : System.ServiceModel.ClientBase<AFLStock.WCF.Client.ServiceReference.IAFLStockService>, AFLStock.WCF.Client.ServiceReference.IAFLStockService {
        
        public AFLStockServiceClient() {
        }
        
        public AFLStockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AFLStockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AFLStockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AFLStockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AFLStock.WCF.Client.ServiceReference.PurchaseOrder_POCO[] GetPurchaseOrders_Simplified() {
            return base.Channel.GetPurchaseOrders_Simplified();
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.PurchaseOrder_POCO[]> GetPurchaseOrders_SimplifiedAsync() {
            return base.Channel.GetPurchaseOrders_SimplifiedAsync();
        }
        
        public AFLStock.WCF.Client.ServiceReference.SalesOrder_POCO[] GetSalesOrders_Simplified() {
            return base.Channel.GetSalesOrders_Simplified();
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.SalesOrder_POCO[]> GetSalesOrders_SimplifiedAsync() {
            return base.Channel.GetSalesOrders_SimplifiedAsync();
        }
        
        public double TotalStockValue() {
            return base.Channel.TotalStockValue();
        }
        
        public System.Threading.Tasks.Task<double> TotalStockValueAsync() {
            return base.Channel.TotalStockValueAsync();
        }
        
        public AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsAll_Simplified() {
            return base.Channel.GetStockItemsAll_Simplified();
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsAll_SimplifiedAsync() {
            return base.Channel.GetStockItemsAll_SimplifiedAsync();
        }
        
        public AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategory_Simplified(int catID) {
            return base.Channel.GetStockItemsByCategory_Simplified(catID);
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategory_SimplifiedAsync(int catID) {
            return base.Channel.GetStockItemsByCategory_SimplifiedAsync(catID);
        }
        
        public AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategoryDesignNumber_Simplified(int catID, string designNumber) {
            return base.Channel.GetStockItemsByCategoryDesignNumber_Simplified(catID, designNumber);
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategoryDesignNumber_SimplifiedAsync(int catID, string designNumber) {
            return base.Channel.GetStockItemsByCategoryDesignNumber_SimplifiedAsync(catID, designNumber);
        }
        
        public AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[] GetStockItemsByCategoryDesignNumberSubCode_Simplified(int catID, string designNumber, string subCode) {
            return base.Channel.GetStockItemsByCategoryDesignNumberSubCode_Simplified(catID, designNumber, subCode);
        }
        
        public System.Threading.Tasks.Task<AFLStock.WCF.Client.ServiceReference.StockItemMaster_POCO[]> GetStockItemsByCategoryDesignNumberSubCode_SimplifiedAsync(int catID, string designNumber, string subCode) {
            return base.Channel.GetStockItemsByCategoryDesignNumberSubCode_SimplifiedAsync(catID, designNumber, subCode);
        }
    }
}
